[package]
name = "prj2"
version = "0.1.0"
authors = ["Aaron Weiss <awe@pdgn.co>"]
edition = "2018"

[dependencies]
bytes = "0.4"
clap = "2.33"
fehler = "1.0.0-alpha.1"
futures-preview = "0.3.0-alpha.19"
futures-util-preview = "0.3.0-alpha.19"
rand = "0.7"
tokio = "0.2.0-alpha.6"